"use strict";
let car = 'subaru';
let course = 'GIAIC';
let number = 101;
let string = "I am motivated";
let percentage = 95.5;
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is course == 'GIAIC'? I predict True. ");
console.log(course == 'GIAIC');
console.log("Is number == 101? I predict True. ");
console.log(number == 101);
console.log("Is string == 'I am motivated'? I predict True. ");
console.log(string == "I am motivated");
console.log("Is percentage == '95.5'? I predict True. ");
console.log(percentage == 95.5);
console.log("Is car == 'honda civic'? I predict False.");
console.log(car == 'honda civic');
console.log("Is course == 'PIAIC'? I predict False. ");
console.log(course == 'PIAIC');
console.log("Is number == 100? I predict False. ");
console.log(number == 100);
console.log("Is string == 'I am not motivated'? I predict False ");
console.log(string == "I am not motivated");
console.log("Is percentage == '99.5'? I predict False. ");
console.log(percentage == 99.5);
